# Generated by Django 5.1.3 on 2025-06-02 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preference',
        ),
    ]
